#!/bin/bash

# Make sure that the user gave us a single argument
if [ "$1" == "" ] || [ $# -gt 1 ]; then
  echo
  echo "Usage: wpsql /path/to/wp-config.php"
  echo
  exit 1
fi

# On a Mac running MAMP we need to call mysql from the Applications directory,
# but on linux we can just run 'mysql'
current_os=$(uname)
if [ $current_os == "Darwin" ]; then
  mysql=/Applications/MAMP/Library/bin/mysql;
else
  mysql=$(which mysql)
fi

# setup our variables from the file given to us as an argument
# but lets just make sure we have a valid wp-config.php file
if [ -e $1 ]; then
  sqlname=$(grep DB_NAME $1 | cut -d, -f2 | sed -e 's/^..//' -e 's/....$//')
  sqluser=$(grep DB_USER $1 | cut -d, -f2 | sed -e 's/^..//' -e 's/....$//')
  sqlhost=$(grep DB_HOST $1 | cut -d, -f2 | sed -e 's/^..//' -e 's/....$//')
  sqlpass=$(grep DB_PASSWORD $1 | cut -d, -f2 | sed -e 's/^..//' -e 's/....$//')
else
  echo
  echo "I don't think you supplied a valid wp-config.php file, please call Mark Jaquith for support."
  echo
  exit 2
fi

# Only start mysql if we successfully extracted our variables above
if [ $sqlname != "" ]; then
  $mysql -h $sqlhost -u $sqluser -p$sqlpass $sqlname
else
  echo
  echo "I don't think you supplied a valid wp-config.php file, please call Mark Jaquith for support."
  echo
  exit 3
fi

