#!/bin/bash
sqlname=`grep "define.*DB_NAME" $1 | awk -F"[,'\"]" '{print $5}'`
sqluser=`grep "define.*DB_USER" $1 | awk -F"[,'\"]" '{print $5}'`
sqlhost=`grep "define.*DB_HOST" $1 | awk -F"[,'\"]" '{print $5}'`
sqlpass=`grep "define.*DB_PASSWORD" $1 | awk -F"[,'\"]" '{print $5}'`

mysql -h $sqlhost -u $sqluser -p$sqlpass $sqlname
